---
title: "01 Fitness"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggpubr)
library(GGally)
library(cowplot)
library(ggpointdensity)
library(viridis)
library(data.table)

```

```{r}
load("source_variables.RData")
load(paste0(results_newdata,"all_data.Rdata"))
load(paste0(results_newdata,"all_singles_ca.Rdata"))

output_dir_fig <- paste0(results_path, "Fig1/")
dir.create(output_dir_fig, showWarnings = FALSE, recursive = TRUE)
output_dir_figS <- paste0(results_path, "FigS1/")
dir.create(output_dir_figS, showWarnings = FALSE, recursive = TRUE)

```


# Replicate correlation
```{r ,warning=FALSE,message = FALSE,fig.width=15, fig.height=12}
fitness_col <- c("fitness1_uncorr", "fitness2_uncorr", "fitness3_uncorr")
plots <- list()
r_values_list <- list()

for (i in seq_along(kinases)) {
	if (kinases[i] == "SRC") next
	plots_kin <- list()

	for (j in seq_along(full_assays)) {
		subtable <- all_fitness[kinase == kinases[i] & assay == full_assays[j]]

		if (nrow(subtable) > 0) {
			p_corr_i <- plot_corr_rep(subtable, fitness_col, kinases[i], full_assays[j])
			plots_kin[[j]] <- p_corr_i

			cor_mat <- cor(
				subtable[, ..fitness_col],
				use = "pairwise.complete.obs",
				method = "pearson"
			)

			r_values_list[[paste0(kinases[i], "_", full_assays[j])]] <- data.table(
				kinase = kinases[i],
				assay = full_assays[j],
				R_1v2 = cor_mat[1, 2],
				R_1v3 = cor_mat[1, 3],
				R_2v3 = cor_mat[2, 3]
			)
		}
	}

	plots[[i]] <- plots_kin
}

correlations <- unlist(plots, recursive = FALSE)

correlations <- correlations[!sapply(correlations, is.null)]

correlations_a <- plot_grid(plotlist = lapply(correlations, function(x) ggmatrix_gtable(x)), ncol = 2, nrow = 4)

ggsave(correlations_a, filename = paste0(output_dir_figS, "FigS1B_replicates_all.png"), height = 12, width = 6)

```

```{r}
r_values_dt <- rbindlist(r_values_list)
print(r_values_dt)

r_values_singles <- rbindlist(lapply(setdiff(kinases, "SRC"), function(k) rbindlist(lapply(full_assays, function(a) {
  cor_mat <- cor(all_fitness[kinase == k & assay == a & Nham_aa == 1 & STOP == FALSE, ..fitness_col], use = "pairwise.complete.obs", method = "pearson")
  data.table(kinase = k, assay = a, R_1v2 = cor_mat[1, 2], R_1v3 = cor_mat[1, 3], R_2v3 = cor_mat[2, 3])
}))))

for (a in full_assays) {
  cat("Replicate median r,", a, "| single mutants:",
      round(median(as.matrix(r_values_singles[assay == a, .(R_1v2, R_1v3, R_2v3)])), 3),
      "| full dataset:",
      round(median(as.matrix(r_values_dt[assay == a, .(R_1v2, R_1v3, R_2v3)])), 3), "\n")
}
```


## ZAK

```{r ,warning=FALSE,message = FALSE,fig.width=15, fig.height=12}
fitness_col <- c("fitness1_uncorr", "fitness2_uncorr", "fitness3_uncorr")
subtable <- all_fitness[kinase == "ZAK" & assay == "activity"]
cor_rep_zak<-plot_corr_rep(subtable, fitness_col, "ZAK", "activity")
cor_rep_zak<-cor_rep_zak+theme(plot.title=element_blank())
ggsave(cor_rep_zak, filename = paste0(output_dir_fig, "Fig1G_replicates_activity", format_img), height = 3, width = 3.2)


subtable <- all_fitness[kinase == "ZAK" & assay == "abundance"]
cor_rep_zak<-plot_corr_rep(subtable, fitness_col, "ZAK", "abundance")
cor_rep_zak<-cor_rep_zak+theme(plot.title=element_blank())
ggsave(cor_rep_zak, filename = paste0(output_dir_fig, "Fig1G_replicates_abundance", format_img), height = 3, width = 3.2)
```


# Fitness distributions

```{r,warning=FALSE,message = FALSE,fig.width=10, fig.height=6}
distribution_fitness <- rbindlist(list(
  all_singles_noSTOP[, .(fitness, dataset, kinase, assay)],
  stops[, .(fitness, dataset, kinase, assay)],
  all_synonymous[, .(fitness, dataset, kinase, assay)],
  all_doubles[,.(fitness,dataset,kinase,assay)]
))
```

## ZAK
```{r,warning=FALSE,message = FALSE,fig.width=10, fig.height=6}
subtable <- distribution_fitness[kinase == "ZAK"]

levels_f=c("stops", "synonymous", "singles","doubles")
subtable[,dataset:=factor(dataset,levels=levels_f)]
mean_stats <- subtable[, .(avg_fitness = mean(fitness, na.rm = TRUE)), by = .(assay, dataset)]
colours=c("stops" = "#F8766D", "synonymous" = "#00BA38", "singles" = "#619CFF","doubles"="darkblue")
p_dist_ddg <- ggplot(subtable[dataset%in%c("singles","doubles")], aes(x = fitness, colour = dataset, fill = dataset)) +
  geom_density(alpha = 0.1, linewidth = 1) +

  geom_vline(xintercept = 0, color = "gray", linewidth = 0.6, linetype = "dashed") +

  geom_vline(data = mean_stats[dataset == "synonymous"],
             aes(xintercept = avg_fitness),
             color = "#00BA38", linewidth = 1, linetype = "dashed") +

  geom_vline(data = mean_stats[dataset == "stops"],
             aes(xintercept = avg_fitness),
             color = "#F8766D", linewidth = 1, linetype = "dashed") +

  theme_classic() +
  scale_color_manual(values = colours, name = "") +
  scale_fill_manual(values = colours, name = "") +
  theme(legend.position = "top",
        legend.text = element_text(size = 13, color = "black"),
        axis.text = element_text(size = 13, color = "black"),
        axis.title.x = element_text(size = 14, color = "black"),
        strip.text=element_text(size = 14,color="black",face = "bold")
        ) +
  labs(x = "Fitness", y = "") +
  facet_grid(~assay)

ggsave(p_dist_ddg, filename = paste0(output_dir_fig, "Fig1H_fitness_distribution", format_img), height = 4, width = 6)

```
## All kinases
```{r}
colours <- c("stops" = "#F8766D", "synonymous" = "#00BA38",
             "singles" = "#619CFF", "doubles" = "darkblue")
levels_f <- c("stops", "synonymous", "singles", "doubles")

plot_list_dist <- list()

for (kin in kinases) {
  if (kin == "SRC") next
  subtable <- distribution_fitness[kinase == kin]

  subtable[, dataset := factor(dataset, levels = levels_f)]

  mean_stats <- subtable[, .(avg_fitness = mean(fitness, na.rm = TRUE)), by = .(assay, dataset)]

  p <- ggplot(subtable[dataset %in% c("singles", "doubles")],
              aes(x = fitness, colour = dataset, fill = dataset)) +

    geom_density(alpha = 0.1, linewidth = 1) +

    geom_vline(xintercept = 0, color = "gray", linewidth = 0.6, linetype = "dashed") +

    geom_vline(data = mean_stats[dataset == "synonymous"],
               aes(xintercept = avg_fitness),
               color = "#00BA38", linewidth = 0.8, linetype = "dashed") +

    geom_vline(data = mean_stats[dataset == "stops"],
               aes(xintercept = avg_fitness),
               color = "#F8766D", linewidth = 0.8, linetype = "dashed") +

    theme_classic() +
    scale_color_manual(values = colours, name = "") +
    scale_fill_manual(values = colours, name = "") +
    theme(
      legend.position = "top",
      legend.text = element_text(size = 13, color = "black"),
      axis.text = element_text(size = 13, color = "black"),
      axis.title.x = element_text(size = 14, color = "black"),
      strip.text = element_text(size = 14, color = "black", face = "bold"),
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold")
    ) +
    labs(x = "Fitness", y = "Density", title = relabel_jnk2(kin)) +
    facet_grid(~assay)+
    coord_cartesian(xlim = c(-1, 0.5))

  plot_list_dist[[kin]] <- p
}


final_plot <- ggarrange(plotlist = plot_list_dist, ncol = 1,nrow=4, common.legend = TRUE, legend = "top")
ggsave(final_plot, filename = paste0(output_dir_figS, "FigS1C_fitness_distributions", format_img), height = 13, width = 5)

```


# Per-position fitness

## Weighted mean and median

```{r weighted_mean,warning=FALSE,message = FALSE}
subs_wmean_dt <- all_singles_ca[, .(mean = weighted.mean(fitness_norm, sigma^-2, na.rm = TRUE)),
                                by = .(Pos, kinase, assay, Pos_al, WT_AA)]
wmean_dt <- merge(all_singles_ca, subs_wmean_dt,
                  by = c("Pos", "kinase", "assay", "Pos_al", "WT_AA"),
                  all.x = TRUE)
save(wmean_dt, file = paste0(results_newdata, "singles_weighted_mean.Rdata"))


subs_median_dt <- all_singles_ca[, .(median = median(fitness_norm, na.rm = TRUE)),
                                 by = .(Pos, kinase, assay, Pos_al, WT_AA)]
median_dt <- merge(all_singles_ca, subs_median_dt,
                   by = c("Pos", "kinase", "assay", "Pos_al", "WT_AA"),
                   all.x = TRUE)
save(median_dt, file = paste0(results_newdata, "singles_median.Rdata"))


```


## Activity heatmap

```{r heatmap_act_wm,fig.width=50, fig.height=4}
load(file = paste0(results_newdata, "alignment_pos.Rdata"))
al_ref <- unique(alignment_pos[, .(Pos_al, kinase, WT_AA)])
full_grid <- merge(CJ(Pos_al = unique(al_ref$Pos_al), kinase = kinases),
                   al_ref, by = c("Pos_al", "kinase"), all.x = TRUE)
full_grid <- full_grid[is.na(WT_AA) | WT_AA != "-"]

activity_all_wm <- merge(full_grid, subs_median_dt[assay == "activity", .(Pos_al, kinase, median)],
                         by = c("Pos_al", "kinase"), all.x = TRUE)
fitness_val<- activity_all_wm[!is.na(median), median]

activity_all_wm[, pos_group := ifelse(Pos_al <= 127, "First", ifelse(Pos_al <= 252, "Second", "Third"))]
cap_val <- max(abs(quantile(fitness_val, probs = c(0.01, 0.99))))

cols <- colorRampPalette(c("brown3", "gray92", "blue3"))(100)
p_heatmap_wm<-ggplot(activity_all_wm)+
  geom_tile(aes(x=as.factor(Pos_al),y=factor(kinase, levels=rev(kinases)),fill=median),color="white", size=0.1)+
  theme_classic()+
  theme()+
  labs(x="", y="", fill="Median\nfitness ",title = "Activity fitness median per position")+
  theme(axis.ticks.y=element_blank(),
        plot.title =element_text(size=25),
        panel.grid = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_text(size=15,face="bold"),
        legend.text = element_text(size=15),
        axis.text.y = element_text(size=20),
        axis.text.x = element_text(size=10,angle = 90, vjust = 0.5, hjust=1),
        axis.title = element_text(size = 11),
        strip.text=element_blank()
        )+
  geom_text(aes(x=as.factor(Pos_al),y=kinase,label=WT_AA), size=4)+
  scale_fill_gradientn(
    colours = cols,
    limits = c(-cap_val, cap_val),
    oob = scales::squish,
    na.value = "grey64"
  )+scale_y_discrete(labels = relabel_jnk2)+facet_wrap(~pos_group,ncol=1,scales = "free_x")

ggsave(p_heatmap_wm,filename =paste0(output_dir_figS,"FigS1G_activity_median",format_img),height = 7,width = 20,limitsize = FALSE)
```

## Abundance heatmap

```{r heatmap_abund_wm,fig.width=50, fig.height=4}
abundance_all_wm <- merge(full_grid, subs_median_dt[assay == "abundance", .(Pos_al, kinase, median)],
                          by = c("Pos_al", "kinase"), all.x = TRUE)
fitness_val<- abundance_all_wm[!is.na(median), median]

cap_val <- max(abs(quantile(fitness_val, probs = c(0.01, 0.80))))
abundance_all_wm[, pos_group := ifelse(Pos_al <= 127, "First", ifelse(Pos_al <= 252, "Second", "Third"))]

cols <- colorRampPalette(c("brown3", "gray92", "blue3"))(100)
p_heatmap_wm<-ggplot(abundance_all_wm)+
  geom_tile(aes(x=as.factor(Pos_al),y=factor(kinase, levels=rev(kinases)),fill=median),color="white", size=0.1)+
  theme_classic()+
  theme()+
  labs(x="", y="", fill="Median\nfitness ",title = "Abundance fitness median per position")+
  theme(axis.ticks.y=element_blank(),
        axis.ticks.x.top = element_line(),
        plot.title =element_text(size=25),
        panel.grid = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_text(size=15,face="bold"),
        legend.text = element_text(size=15),
        axis.text.y = element_text(size=20),
        axis.text.x = element_text(size=10,angle = 90, vjust = 0.5, hjust=1),
        axis.title = element_text(size = 11),
                strip.text=element_blank()
)+
  geom_text(aes(x=as.factor(Pos_al),y=kinase,label=WT_AA), size=4)+
  scale_fill_gradientn(
    colours = cols,
    limits = c(-cap_val, cap_val),
    oob = scales::squish,
    na.value = "grey64"
  )+scale_y_discrete(labels = relabel_jnk2)+facet_wrap(~pos_group,ncol=1,scales = "free_x")

ggsave(p_heatmap_wm,filename =paste0(output_dir_figS,"FigS1F_abundance_median",format_img),height = 7,width = 20,limitsize = FALSE)
```
# Variant counts

```{r}
aa_per_assay <- all_fitness[kinase %in% kinases & Nham_aa >= 1, .N, by = assay][order(assay)]
cat("aa-variant count (activity):", aa_per_assay[assay == "activity", N], "\n")
cat("aa-variant count (abundance):", aa_per_assay[assay == "abundance", N], "\n")

fitness_root <-  data_fitness
immediate_folders <- list.dirs(fitness_root, recursive = FALSE)

file_paths <- list.files(
	path = immediate_folders,
	pattern = "fitness_doubles\\.txt$",
	recursive = FALSE,
	full.names = TRUE
)

all_doubles <- rbindlist(lapply(file_paths, function(fp) {

	dt <- fread(fp)

	folder_name <- basename(dirname(fp))

	dt[, kinase_folder := folder_name]

	return(dt)

}), use.names = TRUE, fill = TRUE)
```

# Backgrounds per substitution

```{r}
backgrounds <- fread(paste0(data_struct,"backgrounds.csv"))

mut_pair_counts_filtered <- rbindlist(list(
	all_doubles[, .(kinase_folder, Pos = Pos1, Mut = Mut1, bg_Pos = Pos2, bg_Mut = Mut2)],
	all_doubles[, .(kinase_folder, Pos = Pos2, Mut = Mut2, bg_Pos = Pos1, bg_Mut = Mut1)]
))[, base_kinase := sub("_.*", "", kinase_folder)
][backgrounds, on = .(base_kinase = kinase, bg_Pos = Pos, bg_Mut = Mut), nomatch = NULL
][, .(n_paired_mutations = uniqueN(paste(bg_Pos, bg_Mut))), by = .(kinase_folder, Pos, Mut)]

all_folders <- unique(mut_pair_counts_filtered$kinase_folder)

ordered_folders <- all_folders[order(
	match(sub("_.*", "", all_folders), kinases),
	sub(".*_", "", all_folders)
)]

mut_pair_counts_filtered[, kinase_folder := factor(kinase_folder, levels = ordered_folders)]


p_dist_discrete <- ggplot(mut_pair_counts_filtered, aes(x = n_paired_mutations)) +

	geom_bar(color = "black", alpha = 0.7) +

	scale_x_continuous(breaks = 1:8, limits = c(0.5, 8.5)) +

	facet_wrap(~ kinase_folder, ncol = 4, labeller = lab_kinase) +

	theme_classic(base_size = 14) +

	labs(
		x = "Number backgrounds",
		y = "Frequency"
	) +

	theme(
		legend.position = "none",
		strip.text = element_text(face = "bold")
	)

ggsave(p_dist_discrete,filename =paste0(output_dir_figS,"FigS1E_backgrounds",format_img),height =5,width = 10,limitsize = FALSE)

cat("Median backgrounds per single substitution:", median(mut_pair_counts_filtered$n_paired_mutations), "\n")
```


# Pilot

## Read data

```{r}
kinases_pilot<-c("FGR","MAPK9","TSSK2","ZAK")

pilot<-fread(paste0(results_newdata,"pilot_singles.csv"))
pilot_syn<-fread(paste0(results_newdata,"pilot_syn.csv"))
pilot[,fitness:=-fitness]
pilot_syn[,fitness:=-fitness]
```

## Normalisation

```{r}
stops<-pilot[Mut=="*"]

normalization <- function(kin_name) {

	mean_stop_kin <- stops[kinase == kin_name, weighted.mean(fitness, sigma^-2, na.rm = TRUE)]
	mean_syn_kin  <- pilot_syn[kinase == kin_name, weighted.mean(fitness, sigma^-2, na.rm = TRUE)]

	mean_stop_FGR <- stops[kinase == "FGR", weighted.mean(fitness, sigma^-2, na.rm = TRUE)]
	mean_syn_FGR  <- pilot_syn[kinase == "FGR", weighted.mean(fitness, sigma^-2, na.rm = TRUE)]

	linear_points <- data.frame(
		kin = c(mean_syn_kin, mean_stop_kin),
		FGR = c(mean_syn_FGR, mean_stop_FGR)
	)

	lm_fit <- lm(FGR ~ kin, data = linear_points)

	target_fitness <- pilot[kinase == kin_name, fitness]
	fitness_c <- predict(lm_fit, newdata = data.frame(kin = target_fitness))

	return(data.table(
		real = target_fitness,
		normalised = fitness_c
	))
}

fitness_c<-NULL
for (i in kinases_pilot){
  fitness_c<-rbind(fitness_c,normalization(i))
}


all_singles_c<-cbind(pilot,fitness_c$normalised)
colnames(all_singles_c)<-c(colnames(pilot),"fitness_norm")
```


```{r}
heatmap_singles<-all_singles_c
heatmap_singles$label<-""
heatmap_singles$label<-ifelse(!is.na(heatmap_singles$WT_AA) & (heatmap_singles$WT_AA == heatmap_singles$Mut),"*","")


```

## Alignment

```{r}
dt_positions <- data.table(
	kinase = c("FGR", "MAPK9", "TSSK2", "ZAK"),
	Pos_full = c(8, 18, 9, 14)
)

heatmap_singles[dt_positions,
	Pos_absolute := Pos + i.Pos_full - 1,
	on = "kinase"
]


setnames(heatmap_singles,"Pos","ind_pos")
setnames(heatmap_singles,"Pos_absolute","Pos")

heatmap_singles <- merge(
  heatmap_singles, alignment_pos,
  by = c("Pos", "kinase", "WT_AA"),
  all.x = TRUE
)

all_combos <- CJ(
	Pos_al = unique(heatmap_singles$Pos_al),
	kinase = unique(heatmap_singles$kinase)
)

heatmap_singles <- heatmap_singles[all_combos, on = c("Pos_al", "kinase")]

heatmap_singles[is.na(WT_AA), WT_AA := "-"]

```


## Heatmaps

```{r}
heatmap_singles<-heatmap_singles[Pos_al>24&Pos_al<89]
heatmap_singles[,Pos_al_pilot:=Pos_al-24]

cap_val <- max(abs(quantile(heatmap_singles$fitness_norm,na.rm=T, probs = c(0.05, 0.95))))
cols <- colorRampPalette(c("brown3", "gray92", "blue3"))(100)

plot_heatmap <- function(subtable, kin){

	axis_data <- unique(subtable[, .(Pos_al_pilot, WT_AA)])
	axis_data <- axis_data[order(Pos_al_pilot)]

	p_heatmap <- ggplot(subtable) +
		geom_tile(aes(x = Pos_al_pilot, y = factor(Mut, levels = rev(all_aa)), fill = fitness_norm), color = "white", size = 0.1) +
		theme_minimal() +
		labs(x = "", y = "", fill = "Fitness", title = paste0(relabel_jnk2(kin), " ")) +
		theme(
			axis.ticks.y = element_blank(),
			axis.ticks.x.top = element_line(),
			panel.grid = element_blank(),
			panel.grid.major = element_blank(),
			panel.grid.minor = element_blank(),
			legend.title = element_text(size = 13),
			legend.text = element_text(size = 10),
			axis.text.y = element_text(color = color_axis_y, size = 7),
			axis.text.x = element_text(size = 7),
			axis.title = element_text(size = 13),
			panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
			title = element_text(size = 12)
		) +
		geom_text(aes(Pos_al_pilot, factor(Mut, levels = rev(all_aa)), label = label), size = 7) +
		geom_point(
			data = unique(subtable[ATP == "ATP contact", .(Pos_al_pilot)]),
			aes(x = Pos_al_pilot, y = length(all_aa) + 0.2),
			inherit.aes = FALSE, shape = 16, colour = "grey50", size = 2
		) +
		scale_fill_gradientn(
			colours = cols,
			limits = c(-cap_val, cap_val),
			oob = scales::squish,
			na.value = "grey64"
		) +
		scale_x_continuous(
			breaks = axis_data$Pos_al_pilot,
			labels = axis_data$WT_AA,
			expand = c(0,0)
		)+
	  scale_y_discrete(na.translate = FALSE, expand = expansion(mult = c(0, 0.1)))

	return(p_heatmap)
}


structural_info <- fread(paste0(data_struct, "structural_features.csv"))
as_annot <- unique(structural_info[, .(kinase, Pos_al, ATP)])

plots<-list()
for(j in 2:length(kinases)){
subtable <- heatmap_singles[(Mut != "*" | is.na(Mut)) & kinase == kinases[j]]
subtable <- merge(subtable, as_annot, by = c("kinase","Pos_al"), all.x = TRUE)
if(nrow(subtable) > 0) {
    plot_i<-plot_heatmap(subtable, kinases[j])
    plots[[j]]<-plot_i
  }
}


heatmaps_pilot<-do.call(c, plots)

all_heatmaps_pilot<-ggarrange(plotlist = heatmaps_pilot,ncol=1,nrow=4,common.legend = T)

ggsave(all_heatmaps_pilot,filename =paste0(output_dir_figS,"FigS1A_pilot_heatmaps",format_img),height =10,width = 5,limitsize = FALSE)


```

## ATP contact vs other positions

```{r}
heatmap_singles_struc <- merge(heatmap_singles, structural_info, by = c("kinase", "Pos","Pos_al"),all.x=TRUE)

plot_data <- heatmap_singles_struc[!is.na(ATP) & Mut != "*"]
plot_data[, ATP_factor := as.factor(ATP)]

my_comparisons <- list(levels(plot_data$ATP_factor))

p_pilot <- ggplot(plot_data, aes(x = ATP_factor, y = fitness_norm)) +

	geom_violin(aes(fill = ATP_factor), alpha = 0.8, color = "black", trim = TRUE) +
	geom_boxplot(width = 0.12, fill = "white", color = "black", outlier.shape = NA, alpha = 0.8) +

	stat_compare_means(
		comparisons = my_comparisons,
		method = "wilcox.test",
		label = "p.format",
		label.y=0.6
		) +

	facet_wrap(~kinase, nrow = 1, labeller = lab_kinase) +
	scale_fill_manual(values = c("#ffe500", "indianred3")) +
	scale_color_manual(values = c("yellow3", "indianred4")) +

	theme_classic(base_size = 14) +
	labs(
		x = "",
		y = "Normalized Fitness"
	) +

	theme(
		legend.position = "none",
		strip.background = element_rect(fill = "white", color = "black", linewidth = 1),
		strip.text = element_text(face = "bold", size = 12),
		axis.text.x = element_text(size = 11, angle = 45, hjust = 1, vjust = 1),
		axis.text.y = element_text(size = 11),
		panel.border = element_rect(color = "black", fill = NA, linewidth = 1)
	)


ggsave(p_pilot,filename =paste0(output_dir_figS,"FigS1D_pilot_ATP_violins",format_img),height =4,width = 6,limitsize = FALSE)

```

## ATP contact vs other positions: medians and Wilcoxon test

```{r atp_pilot_summary}
sub_atp <- plot_data[Mut != "*" & !is.na(fitness_norm)]

medians_atp <- sub_atp[, .(median_fitness_norm = median(fitness_norm),
                           q25 = quantile(fitness_norm, 0.25),
                           q75 = quantile(fitness_norm, 0.75),
                           n   = .N),
                       by = .(kinase, ATP)][order(kinase, ATP)]
print(medians_atp)

wilcox_atp <- sub_atp[, {
  g <- split(fitness_norm, ATP)
  if (length(g) == 2 && all(lengths(g) >= 2)) {
    w <- wilcox.test(g[[1]], g[[2]], alternative = "two.sided", exact = FALSE)
    list(p_value = w$p.value,
         statistic = unname(w$statistic))
  } else {
    list(p_value = NA_real_, statistic = NA_real_)
  }
}, by = kinase][order(kinase)]

print(wilcox_atp)
```
